import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { UserProvider } from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LK EAD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-[#f6f6f6] text-white">
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
